"""Download the webfonts from Google Fonts and rewrite them as local @font-face.

Google Fonts is the only third-party request the site makes, and it sends every
visitor's IP to Google before they have consented to anything — a routine GDPR
complaint, and an odd look on a page whose pitch is that it takes nothing it
doesn't need. Self-hosting removes it, so the page makes zero third-party
requests.

Fetches the same optimised woff2 files Google serves rather than converting the
TTFs by hand: they are already hinted and subsetted, and matching Google's
output means the rendering does not change.

Only latin and latin-ext are kept. The other five subsets (cyrillic, greek,
vietnamese and their extended forms) are ~60% of the bytes and cover scripts
this UI never renders.

    python3 scripts/vendor-fonts.py
"""

import hashlib
import pathlib
import re
import urllib.request

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Mozilla+Text:wght@400;500;600;700"
    "&family=Inter:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500"
    "&display=swap"
)
KEEP = {"latin", "latin-ext"}

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "public" / "fonts"
OUT_CSS = REPO / "src" / "app" / "fonts.css"


def get(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})
    ).read()


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css = get(CSS_URL).decode()

    # Each block is preceded by a /* subset */ comment.
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)

    out, total = [], 0
    out.append(
        "/* Generated by scripts/vendor-fonts.py — do not edit by hand.\n"
        " * Self-hosted so the page makes no third-party requests. Re-run the\n"
        " * script to change families or weights. */\n"
    )

    # Google now ships one *variable* woff2 per family+subset, so every weight
    # of a family resolves to the same bytes — naming files per weight
    # downloaded the same file four times and shipped four copies. Deduped on
    # content hash: one file, referenced by every weight declaration.
    by_hash: dict[str, str] = {}

    for subset, block in blocks:
        if subset not in KEEP:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        data = get(url)
        digest = hashlib.md5(data).hexdigest()
        if digest not in by_hash:
            name = f"{family.lower().replace(' ', '-')}-{subset}.woff2"
            (OUT_DIR / name).write_bytes(data)
            by_hash[digest] = name
            total += len(data)

        out.append(block.replace(url, f"/fonts/{by_hash[digest]}").strip() + "\n")

    OUT_CSS.write_text("\n".join(out), encoding="utf8")
    files = len(list(OUT_DIR.glob("*.woff2")))
    print(f"wrote {files} woff2 files, {total // 1024} KB total")
    print(f"wrote {OUT_CSS.relative_to(REPO)}")


if __name__ == "__main__":
    main()
